#!/usr/bin/env python3
"""Keep every installed base-agents package's declared harness permissions converged on this machine.

Enumerates every installed `base-agents` package root across Claude's plugin scopes
(`installed_plugins.json`) and the Codex plugin cache, renders each root's `harness.json`
`requires.permissions` templates against that root, and converges `~/.claude/settings.json`
`permissions.allow` (tracked through a `~/.agents-state/harness-permissions.json` sidecar so
user-authored allow rules are never touched) and `~/.codex/rules/base-agents.rules`. Writes only on
drift. `--apply` is what hooks and launchers run and always exits 0; `--check` reports drift with a
non-zero exit for CI/diagnostic use, except that an unreadable or malformed target still only warns and
exits 0 rather than writing anything. `--print <script>` prints the exact resolved invocation for a
declared script (by filename) on this machine, one line per installed root, for use in skill prose.

Honours `CLAUDE_CONFIG_DIR`, `CODEX_HOME` and `AGENT_STATE_DIRECTORY` so tests never touch real user
files, and the opt-out `BASE_AGENTS_HARNESS_PERMISSIONS=off`.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import sys
import tempfile
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import harness_permissions


STATE_DIRECTORY_ENV = "AGENT_STATE_DIRECTORY"
OPT_OUT_ENV = "BASE_AGENTS_HARNESS_PERMISSIONS"
MARKETPLACE = "base-agents"
CODEX_RULES_HEADER = (
    "# Generated by base-agents harness_permissions_sync; do not edit. "
    "User rules belong in other files."
)


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, ValueError):
        return None


def write_text_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        os.replace(temp, str(path))
    finally:
        if os.path.exists(temp):
            os.unlink(temp)


def claude_config_root(environ: dict) -> Path:
    configured = environ.get("CLAUDE_CONFIG_DIR")
    return Path(configured).expanduser() if configured else Path.home() / ".claude"


def codex_home(environ: dict) -> Path:
    configured = environ.get("CODEX_HOME")
    return Path(configured).expanduser() if configured else Path.home() / ".codex"


def state_directory(environ: dict) -> Path:
    configured = environ.get(STATE_DIRECTORY_ENV)
    return Path(configured).expanduser() if configured else Path.home() / ".agents-state"


def sidecar_path(environ: dict) -> Path:
    return state_directory(environ) / "harness-permissions.json"


def claude_plugin_roots(environ: dict) -> set[Path]:
    config = claude_config_root(environ)
    data = read_json(config / "plugins" / "installed_plugins.json")
    plugins = data.get("plugins") if isinstance(data, dict) else None
    roots: set[Path] = set()
    if isinstance(plugins, dict):
        for identity, entries in plugins.items():
            if not isinstance(identity, str) or not identity.endswith(f"@{MARKETPLACE}"):
                continue
            if not isinstance(entries, list):
                continue
            for entry in entries:
                if not isinstance(entry, dict):
                    continue
                path = entry.get("installPath")
                if isinstance(path, str) and path:
                    roots.add(Path(path))
    return roots


def codex_plugin_roots(environ: dict) -> set[Path]:
    base = codex_home(environ) / "plugins" / "cache" / MARKETPLACE
    roots: set[Path] = set()
    if not base.is_dir():
        return roots
    try:
        plugin_dirs = list(base.iterdir())
    except OSError:
        return roots
    for plugin_dir in plugin_dirs:
        if not plugin_dir.is_dir() or plugin_dir.name.startswith("plugin-install-"):
            continue
        try:
            version_dirs = list(plugin_dir.iterdir())
        except OSError:
            continue
        for version_dir in version_dirs:
            if version_dir.is_dir() and (version_dir / "harness.json").is_file():
                roots.add(version_dir)
    return roots


def load_requires(root: Path, warnings: list[str]) -> dict | None:
    harness = read_json(root / "harness.json")
    if not isinstance(harness, dict):
        return None
    requires = harness.get("requires")
    try:
        harness_permissions.validate_requires(requires, str(root))
    except Exception as error:  # noqa: BLE001
        warnings.append(f"{root}: ignoring invalid harness declaration ({error})")
        return None
    return requires


def rendered_requirements(roots: set[Path], warnings: list[str]) -> list[dict]:
    requirements = []
    for root in sorted(roots):
        requires = load_requires(root, warnings)
        if requires is None:
            continue
        claude_allow, codex_rules = harness_permissions.render_permissions(requires["permissions"], root)
        requirements.append({"permissions": {"claude_allow": claude_allow, "codex_prefix_rules": codex_rules}})
    return requirements


def desired_permissions(environ: dict, warnings: list[str]) -> tuple[list[str], list[dict]]:
    claude_requirements = rendered_requirements(claude_plugin_roots(environ), warnings)
    codex_requirements = rendered_requirements(codex_plugin_roots(environ), warnings)
    claude_allow, _ = harness_permissions.fold_permissions(claude_requirements)
    _, codex_rules = harness_permissions.fold_permissions(codex_requirements)
    return claude_allow, codex_rules


def load_sidecar(environ: dict, warnings: list[str]) -> dict:
    path = sidecar_path(environ)
    if not path.is_file():
        return {"schema_version": 1, "claude": {}}
    data = read_json(path)
    if not isinstance(data, dict) or data.get("schema_version") != 1 or not isinstance(data.get("claude"), dict):
        warnings.append(f"{path}: ignoring invalid sidecar state")
        return {"schema_version": 1, "claude": {}}
    return data


def save_sidecar(environ: dict, data: dict) -> None:
    write_text_atomic(sidecar_path(environ), json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def claude_target_text(
    path: Path, desired_allow: list[str], sidecar: dict, warnings: list[str]
) -> str | None:
    raw = path.read_text(encoding="utf-8-sig") if path.is_file() else None
    existing: Any = {}
    if raw is not None:
        try:
            existing = json.loads(raw)
        except ValueError as error:
            warnings.append(f"{path}: cannot parse settings ({error}); leaving untouched")
            return None
    if not isinstance(existing, dict):
        warnings.append(f"{path}: settings must be an object; leaving untouched")
        return None
    permissions = existing.get("permissions", {})
    if not isinstance(permissions, dict):
        warnings.append(f"{path}: permissions must be an object; leaving untouched")
        return None
    allow = permissions.get("allow", [])
    if not isinstance(allow, list) or any(not isinstance(item, str) for item in allow):
        warnings.append(f"{path}: permissions.allow must be a string list; leaving untouched")
        return None
    owned_previously = set(sidecar.get("claude", {}).get(str(path), []))
    survivors = [entry for entry in allow if entry not in owned_previously]
    merged = survivors + [entry for entry in sorted(desired_allow) if entry not in survivors]
    if merged == allow:
        return raw
    permissions["allow"] = merged
    existing["permissions"] = permissions
    return json.dumps(existing, indent=2, ensure_ascii=False) + "\n"


def codex_rules_text(rules: list[dict]) -> str | None:
    if not rules:
        return None
    lines = [CODEX_RULES_HEADER, ""]
    lines += harness_permissions.codex_rule_lines(rules)
    return "\n".join(lines)


def current_text(path: Path) -> str | None:
    if not path.is_file():
        return None
    try:
        return path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeError):
        return None


def synchronize(environ: dict, mode: str) -> tuple[list[str], list[str]]:
    if environ.get(OPT_OUT_ENV, "").strip().lower() == "off":
        return [], []
    warnings: list[str] = []
    claude_allow, codex_rules = desired_permissions(environ, warnings)
    sidecar = load_sidecar(environ, warnings)
    claude_path = claude_config_root(environ) / "settings.json"
    claude_expected = claude_target_text(claude_path, claude_allow, sidecar, warnings)
    codex_path = codex_home(environ) / "rules" / "base-agents.rules"
    codex_expected = codex_rules_text(codex_rules)

    drifted: list[str] = []
    if claude_expected is not None:
        if current_text(claude_path) != claude_expected:
            drifted.append(str(claude_path))
            if mode == "apply":
                write_text_atomic(claude_path, claude_expected)
        if mode == "apply":
            sidecar.setdefault("claude", {})[str(claude_path)] = sorted(claude_allow)

    if current_text(codex_path) != codex_expected:
        drifted.append(str(codex_path))
        if mode == "apply":
            if codex_expected is None:
                try:
                    codex_path.unlink()
                except FileNotFoundError:
                    pass
            else:
                write_text_atomic(codex_path, codex_expected)

    if mode == "apply":
        save_sidecar(environ, sidecar)
    return drifted, warnings


def print_invocations(environ: dict, script_name: str) -> tuple[list[str], list[str]]:
    warnings: list[str] = []
    roots = sorted(claude_plugin_roots(environ) | codex_plugin_roots(environ))
    lines: list[str] = []
    for root in roots:
        requires = load_requires(root, warnings)
        if requires is None:
            continue
        for template in requires["permissions"]["claude_allow"]:
            if not (template.startswith("Bash(") and template.endswith(")")):
                continue
            inner = template[len("Bash("):-1]
            if script_name not in inner:
                continue
            forward, _ = harness_permissions.path_spellings(root)
            rendered = inner.replace(harness_permissions.PLUGIN_ROOT_TOKEN, forward)
            if rendered not in lines:
                lines.append(rendered)
    return lines, warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--apply", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--print", dest="print_script", metavar="SCRIPT")
    args = parser.parse_args(argv)
    environ = os.environ
    try:
        if args.print_script:
            lines, warnings = print_invocations(environ, args.print_script)
            for line in lines:
                print(line)
            for warning in warnings:
                print(f"harness-permissions-sync: {warning}", file=sys.stderr)
            return 0
        mode = "apply" if args.apply else "check"
        drifted, warnings = synchronize(environ, mode)
        for warning in warnings:
            print(f"harness-permissions-sync: {warning}", file=sys.stderr)
        if drifted:
            verb = "Updated" if mode == "apply" else "Drift in"
            print(f"harness-permissions-sync: {verb}: " + ", ".join(drifted))
        if mode == "check" and not warnings:
            return 1 if drifted else 0
        return 0
    except Exception as error:  # noqa: BLE001
        print(f"harness-permissions-sync: {error}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
