[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [switch] $VerifyOnly,
    [string] $DocumentsPath = [Environment]::GetFolderPath('MyDocuments')
)

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
$loader = Join-Path $repo 'shell\profile.ps1'

if (-not (Test-Path -LiteralPath $loader -PathType Leaf)) { throw "shell/profile.ps1 missing from $repo" }

$targets = @(
    (Join-Path $DocumentsPath 'WindowsPowerShell\Microsoft.PowerShell_profile.ps1'),
    (Join-Path $DocumentsPath 'PowerShell\Microsoft.PowerShell_profile.ps1')
)

$startMarker = '# >>> base-agents >>>'
$endMarker = '# <<< base-agents <<<'
$escapedLoader = $loader.Replace("'", "''")
$managedBlock = @"
$startMarker
`$baseAgentsShell = '$escapedLoader'
if (Test-Path -LiteralPath `$baseAgentsShell) { . `$baseAgentsShell }
else { Write-Host "profile: base-agents missing at `$baseAgentsShell" -ForegroundColor Red }
$endMarker
"@
$legacyPattern = '(?s)\A# Generated by base-agents/install\.ps1[^\r\n]*\r?\n\$baseAgentsShell = .*?\r?\nif .*?\r?\nelse .*?\r?\n?'

foreach ($target in $targets) {
    $exists = Test-Path -LiteralPath $target -PathType Leaf
    $current = if ($exists) { [IO.File]::ReadAllText($target) } else { '' }
    $hasStart = $current.Contains($startMarker)
    $hasEnd = $current.Contains($endMarker)
    if ($hasStart -xor $hasEnd) { throw "Malformed base-agents profile block: $target" }
    $installed = $hasStart -and $hasEnd -and $current.Contains($loader)

    if ($VerifyOnly) {
        "{0,-70} {1}" -f $target, $(if ($installed) { 'wired' } else { 'NOT wired' })
        continue
    }
    if ($installed) { "already wired: $target"; continue }

    $directory = Split-Path -Parent $target
    if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
        if ($PSCmdlet.ShouldProcess($directory, 'create profile directory')) {
            [void](New-Item -ItemType Directory -Path $directory -Force)
        }
    }

    if ($exists -and $PSCmdlet.ShouldProcess($target, 'back up existing profile')) {
        $stamp = [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmssfff')
        $suffix = [guid]::NewGuid().ToString('N').Substring(0, 8)
        $backup = "$target.pre-base-agents.$stamp.$suffix.bak"
        Copy-Item -LiteralPath $target -Destination $backup
        "backed up: $backup"
    }

    $withoutLegacy = [regex]::Replace($current, $legacyPattern, '')
    if ($hasStart -and $hasEnd) {
        $pattern = [regex]::Escape($startMarker) + '(?s).*?' + [regex]::Escape($endMarker)
        $next = [regex]::Replace($withoutLegacy, $pattern, $managedBlock)
    } else {
        $prefix = $withoutLegacy.TrimEnd()
        $next = if ($prefix) { $prefix + "`r`n`r`n" + $managedBlock } else { $managedBlock }
    }

    if ($PSCmdlet.ShouldProcess($target, 'update base-agents managed profile block')) {
        [IO.File]::WriteAllText($target, $next.TrimEnd() + "`r`n", [Text.UTF8Encoding]::new($false))
        "wired: $target"
    }
}

if ($VerifyOnly) { return }

$probe = "try { . '$escapedLoader'; if (Get-Command cr -ErrorAction SilentlyContinue) { 'ok' } else { 'loaded but cr missing' } } catch { 'FAILED: ' + `$_.Exception.Message }"
$result = & powershell.exe -NoProfile -Command $probe
"load check (5.1): $result"
