[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [switch] $VerifyOnly
)

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
$loader = Join-Path $repo 'shell\profile.ps1'

if (-not (Test-Path $loader)) { throw "shell/profile.ps1 missing from $repo" }

# Both hosts, because Windows PowerShell 5.1 and pwsh 7 read different profile paths and Tommy runs 5.1.
$targets = @(
    (Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'WindowsPowerShell\Microsoft.PowerShell_profile.ps1'),
    (Join-Path ([Environment]::GetFolderPath('MyDocuments')) 'PowerShell\Microsoft.PowerShell_profile.ps1')
)

$stub = @"
# Generated by base-agents/install.ps1 - edit shell/*.ps1 in that repo, not this file.
`$baseAgentsShell = '$loader'
if (Test-Path `$baseAgentsShell) { . `$baseAgentsShell }
else { Write-Host "profile: base-agents missing at `$baseAgentsShell" -ForegroundColor Red }
"@

foreach ($target in $targets) {
    $dir = Split-Path $target -Parent
    $installed = (Test-Path $target) -and ([IO.File]::ReadAllText($target).Contains($loader))

    if ($VerifyOnly) {
        "{0,-70} {1}" -f $target, $(if ($installed) { 'wired' } else { 'NOT wired' })
        continue
    }
    if ($installed) { "already wired: $target"; continue }
    if (-not (Test-Path $dir)) {
        if ($PSCmdlet.ShouldProcess($dir, 'create profile directory')) { [void](New-Item -ItemType Directory -Path $dir -Force) }
    }
    # The profile being replaced is the only copy of whatever was in it, so it is kept beside itself
    # under a name no host loads. Never overwritten on a second run.
    if ((Test-Path $target) -and -not (Test-Path "$target.pre-base-agents.bak")) {
        if ($PSCmdlet.ShouldProcess($target, 'back up existing profile')) {
            Copy-Item -LiteralPath $target -Destination "$target.pre-base-agents.bak"
            "backed up: $target.pre-base-agents.bak"
        }
    }
    if ($PSCmdlet.ShouldProcess($target, 'point at base-agents/shell/profile.ps1')) {
        [IO.File]::WriteAllText($target, $stub)
        "wired: $target"
    }
}

if ($VerifyOnly) { return }

# Proving it loads matters more than proving it was written: a parse error in any shell/*.ps1 takes the
# whole profile out, and the next new terminal is where that would be discovered otherwise.
$probe = "try { . '$loader'; if (Get-Command cr -ErrorAction SilentlyContinue) { 'ok' } else { 'loaded but cr missing' } } catch { 'FAILED: ' + `$_.Exception.Message }"
$result = & powershell.exe -NoProfile -Command $probe
"load check (5.1): $result"
