$ErrorActionPreference = 'Stop'

$repository = Split-Path -Parent $PSScriptRoot
$installer = Join-Path $repository 'install.ps1'
$scratch = Join-Path ([System.IO.Path]::GetTempPath()) "base-agents-install-$([guid]::NewGuid().ToString('N'))"
$legacy = @(
    '# Generated by agent-utilities/install.ps1 - edit shell/*.ps1 in that repo, not this file.'
    '$agentUtilitiesShell = ''C:\source\agent-utilities\shell\profile.ps1'''
    'if (Test-Path $agentUtilitiesShell) { . $agentUtilitiesShell }'
    'else { Write-Host "profile: agent-utilities missing at $agentUtilitiesShell" -ForegroundColor Red }'
) -join "`r`n"

try {
    $targets = @(
        (Join-Path $scratch 'WindowsPowerShell\Microsoft.PowerShell_profile.ps1'),
        (Join-Path $scratch 'PowerShell\Microsoft.PowerShell_profile.ps1')
    )
    foreach ($target in $targets) {
        [void](New-Item -ItemType Directory -Path (Split-Path -Parent $target) -Force)
        [System.IO.File]::WriteAllText($target, $legacy, [System.Text.UTF8Encoding]::new($false))
    }

    & $installer -DocumentsPath $scratch | Out-Null

    foreach ($target in $targets) {
        $content = [System.IO.File]::ReadAllText($target)
        if ($content.Contains('agent-utilities')) { throw "Legacy agent-utilities profile survived in $target." }
        if (-not $content.Contains('# >>> base-agents >>>')) { throw "base-agents block missing from $target." }
        if (-not $content.Contains((Join-Path $repository 'shell\profile.ps1'))) { throw "base-agents loader missing from $target." }
    }

    $verification = @(& $installer -DocumentsPath $scratch -VerifyOnly)
    if (@($verification | Where-Object { $_ -match 'NOT wired' }).Count -ne 0) { throw 'VerifyOnly reported drift.' }
    if (@($verification | Where-Object { $_ -match 'wired' }).Count -ne 2) { throw 'VerifyOnly did not confirm both profiles.' }
} finally {
    if (Test-Path -LiteralPath $scratch) { Remove-Item -LiteralPath $scratch -Recurse -Force }
}

Write-Output 'PASS install.tests.ps1'