#!/usr/bin/env python3
"""Keep every installed tj-agents package's declared harness permissions converged on this machine.

Enumerates every installed package from a marketplace owned by `tj-agents` across Claude's plugin scopes
(`installed_plugins.json` and `known_marketplaces.json`) and the Codex plugin cache and configuration,
renders each root's `harness.json` `requires.permissions` templates against that root, and converges `~/.claude/settings.json`
`permissions.allow` (tracked through a `~/.agents-state/harness-permissions.json` sidecar so
user-authored allow rules are never touched) and `~/.codex/rules/base-agents.rules`. Writes only on
drift. `--apply` is what hooks and launchers run and always exits 0; `--check` reports drift with a
non-zero exit for CI/diagnostic use, except that an unreadable or malformed target still only warns and
exits 0 rather than writing anything. `--print <script>` prints the exact resolved invocation for a
declared script (by filename) on this machine, one line per installed root, for use in skill prose.

Honours `CLAUDE_CONFIG_DIR`, `CODEX_HOME` and `AGENT_STATE_DIRECTORY` so tests never touch real user
files, and the opt-out `BASE_AGENTS_HARNESS_PERMISSIONS=off`.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import harness_permissions


STATE_DIRECTORY_ENV = "AGENT_STATE_DIRECTORY"
OPT_OUT_ENV = "BASE_AGENTS_HARNESS_PERMISSIONS"
TRUSTED_OWNER = "tj-agents"
GITHUB_SOURCE = re.compile(
    r"(?:https://github\.com/|git@github\.com:|ssh://git@github\.com/)?"
    r"(?P<owner>[A-Za-z0-9-]+)/(?P<repo>[A-Za-z0-9_.-]+?)(?:\.git)?/?$",
    re.IGNORECASE,
)
MARKETPLACE_TABLE = re.compile(r'^\s*\[\s*marketplaces\.(?:"(?P<quoted>[^"]+)"|(?P<bare>[A-Za-z0-9_-]+))\s*\]')
STRING_ASSIGNMENT = re.compile(r'^\s*(?P<key>source_type|source|repository)\s*=\s*"(?P<value>[^"]*)"')
CODEX_RULES_HEADER = (
    "# Generated by base-agents harness_permissions_sync; do not edit. "
    "User rules belong in other files."
)


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, ValueError):
        return None


def write_text_atomic(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temp = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        os.replace(temp, str(path))
    finally:
        if os.path.exists(temp):
            os.unlink(temp)


def claude_config_root(environ: dict) -> Path:
    configured = environ.get("CLAUDE_CONFIG_DIR")
    return Path(configured).expanduser() if configured else Path.home() / ".claude"


def codex_home(environ: dict) -> Path:
    configured = environ.get("CODEX_HOME")
    return Path(configured).expanduser() if configured else Path.home() / ".codex"


def state_directory(environ: dict) -> Path:
    configured = environ.get(STATE_DIRECTORY_ENV)
    return Path(configured).expanduser() if configured else Path.home() / ".agents-state"


def sidecar_path(environ: dict) -> Path:
    return state_directory(environ) / "harness-permissions.json"


def github_repository(source: object) -> tuple[str, str] | None:
    match = GITHUB_SOURCE.fullmatch(source) if isinstance(source, str) else None
    if not match or match["repo"] in {".", ".."}:
        return None
    return match["owner"].casefold(), match["repo"].casefold()


def marketplace_repository(source: object) -> tuple[str, str] | None:
    if not isinstance(source, dict):
        return None
    if source.get("source") == "github":
        return github_repository(source.get("repo"))
    if source.get("source") == "git":
        return github_repository(source.get("url"))
    return None


def is_trusted_marketplace(source: object) -> bool:
    repository = marketplace_repository(source)
    return repository is not None and repository[0] == TRUSTED_OWNER


def claude_plugin_roots(environ: dict, warnings: list[str]) -> tuple[set[Path], bool]:
    plugins_directory = claude_config_root(environ) / "plugins"
    path = plugins_directory / "installed_plugins.json"
    if not path.is_file():
        return set(), True
    data = read_json(path)
    plugins = data.get("plugins") if isinstance(data, dict) else None
    if not isinstance(plugins, dict):
        warnings.append(f"{path}: cannot read installed plugin registry; leaving the Claude target untouched")
        return set(), False
    known_path = plugins_directory / "known_marketplaces.json"
    known = read_json(known_path)
    if not isinstance(known, dict):
        warnings.append(f"{known_path}: cannot read marketplace registry; leaving the Claude target untouched")
        return set(), False
    roots: set[Path] = set()
    for identity, entries in plugins.items():
        if not isinstance(identity, str) or "@" not in identity:
            continue
        marketplace = identity.rsplit("@", 1)[1]
        marketplace_entry = known.get(marketplace)
        source = marketplace_entry.get("source") if isinstance(marketplace_entry, dict) else None
        if not is_trusted_marketplace(source):
            continue
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            install_path = entry.get("installPath")
            if isinstance(install_path, str) and install_path:
                roots.add(Path(install_path))
    return roots, True


def codex_marketplaces(environ: dict, warnings: list[str]) -> tuple[set[str], bool]:
    path = codex_home(environ) / "config.toml"
    if not path.is_file():
        return set(), True
    try:
        lines = path.read_text(encoding="utf-8-sig").splitlines()
    except (OSError, UnicodeError) as error:
        warnings.append(f"{path}: cannot read marketplace configuration ({error}); leaving the Codex rules untouched")
        return set(), False
    marketplaces: dict[str, dict[str, str]] = {}
    current: dict[str, str] | None = None
    for line in lines:
        table = MARKETPLACE_TABLE.match(line)
        if table:
            name = table["quoted"] or table["bare"]
            current = marketplaces.setdefault(name, {})
            continue
        if line.lstrip().startswith("["):
            current = None
            continue
        assignment = STRING_ASSIGNMENT.match(line)
        if current is not None and assignment:
            current[assignment["key"]] = assignment["value"]
    trusted = {
        name
        for name, values in marketplaces.items()
        if values.get("source_type") == "git"
        and is_trusted_marketplace({"source": "git", "url": values.get("source")})
    }
    return trusted, True


def codex_plugin_roots(environ: dict, warnings: list[str]) -> tuple[set[Path], bool]:
    trusted_marketplaces, marketplaces_ok = codex_marketplaces(environ, warnings)
    if not marketplaces_ok:
        return set(), False
    base = codex_home(environ) / "plugins" / "cache"
    roots: set[Path] = set()
    if not base.is_dir():
        return roots, True
    try:
        plugin_dirs = list(base.iterdir())
    except OSError as error:
        warnings.append(f"{base}: cannot list the Codex plugin cache ({error}); leaving the Codex rules untouched")
        return roots, False
    for marketplace_dir in plugin_dirs:
        if (
            not marketplace_dir.is_dir()
            or marketplace_dir.name.startswith("plugin-install-")
            or marketplace_dir.name not in trusted_marketplaces
        ):
            continue
        try:
            plugin_dirs = list(marketplace_dir.iterdir())
        except OSError:
            continue
        for plugin_dir in plugin_dirs:
            if not plugin_dir.is_dir() or plugin_dir.name.startswith("plugin-install-"):
                continue
            try:
                version_dirs = list(plugin_dir.iterdir())
            except OSError:
                continue
            for version_dir in version_dirs:
                if version_dir.is_dir() and (version_dir / "harness.json").is_file():
                    roots.add(version_dir)
    return roots, True


def load_requires(root: Path, warnings: list[str]) -> dict | None:
    harness = read_json(root / "harness.json")
    if not isinstance(harness, dict):
        return None
    requires = harness.get("requires")
    try:
        harness_permissions.validate_requires(requires, str(root))
    except Exception as error:  # noqa: BLE001
        warnings.append(f"{root}: ignoring invalid harness declaration ({error})")
        return None
    return requires


def rendered_requirements(roots: set[Path], warnings: list[str]) -> list[dict]:
    requirements = []
    for root in sorted(roots):
        requires = load_requires(root, warnings)
        if requires is None:
            continue
        claude_allow, codex_rules = harness_permissions.render_permissions(requires["permissions"], root)
        requirements.append({"permissions": {"claude_allow": claude_allow, "codex_prefix_rules": codex_rules}})
    return requirements


def desired_permissions(environ: dict, warnings: list[str]) -> tuple[list[str], list[dict], bool, bool]:
    claude_roots, claude_ok = claude_plugin_roots(environ, warnings)
    codex_roots, codex_ok = codex_plugin_roots(environ, warnings)
    claude_requirements = rendered_requirements(claude_roots, warnings)
    codex_requirements = rendered_requirements(codex_roots, warnings)
    claude_allow, _ = harness_permissions.fold_permissions(claude_requirements)
    _, codex_rules = harness_permissions.fold_permissions(codex_requirements)
    return claude_allow, codex_rules, claude_ok, codex_ok


def load_sidecar(environ: dict, warnings: list[str]) -> dict:
    path = sidecar_path(environ)
    if not path.is_file():
        return {"schema_version": 1, "claude": {}}
    data = read_json(path)
    if not isinstance(data, dict) or data.get("schema_version") != 1 or not isinstance(data.get("claude"), dict):
        warnings.append(f"{path}: ignoring invalid sidecar state")
        return {"schema_version": 1, "claude": {}}
    return data


def save_sidecar(environ: dict, data: dict) -> None:
    write_text_atomic(sidecar_path(environ), json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def claude_target_text(
    path: Path, desired_allow: list[str], sidecar: dict, warnings: list[str]
) -> str | None:
    raw = path.read_text(encoding="utf-8-sig") if path.is_file() else None
    existing: Any = {}
    if raw is not None:
        try:
            existing = json.loads(raw)
        except ValueError as error:
            warnings.append(f"{path}: cannot parse settings ({error}); leaving untouched")
            return None
    if not isinstance(existing, dict):
        warnings.append(f"{path}: settings must be an object; leaving untouched")
        return None
    permissions = existing.get("permissions", {})
    if not isinstance(permissions, dict):
        warnings.append(f"{path}: permissions must be an object; leaving untouched")
        return None
    allow = permissions.get("allow", [])
    if not isinstance(allow, list) or any(not isinstance(item, str) for item in allow):
        warnings.append(f"{path}: permissions.allow must be a string list; leaving untouched")
        return None
    owned_previously = set(sidecar.get("claude", {}).get(str(path), []))
    survivors = [entry for entry in allow if entry not in owned_previously]
    merged = survivors + [entry for entry in sorted(desired_allow) if entry not in survivors]
    if merged == allow:
        return raw
    permissions["allow"] = merged
    existing["permissions"] = permissions
    return json.dumps(existing, indent=2, ensure_ascii=False) + "\n"


def codex_rules_text(rules: list[dict]) -> str | None:
    if not rules:
        return None
    lines = [CODEX_RULES_HEADER, ""]
    lines += harness_permissions.codex_rule_lines(rules)
    return "\n".join(lines)


def current_text(path: Path) -> str | None:
    if not path.is_file():
        return None
    try:
        return path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeError):
        return None


def synchronize(environ: dict, mode: str) -> tuple[list[str], list[str]]:
    if environ.get(OPT_OUT_ENV, "").strip().lower() == "off":
        return [], []
    warnings: list[str] = []
    claude_allow, codex_rules, claude_ok, codex_ok = desired_permissions(environ, warnings)
    sidecar = load_sidecar(environ, warnings)
    claude_path = claude_config_root(environ) / "settings.json"
    claude_expected = claude_target_text(claude_path, claude_allow, sidecar, warnings) if claude_ok else None
    codex_path = codex_home(environ) / "rules" / "base-agents.rules"
    codex_expected = codex_rules_text(codex_rules) if codex_ok else None

    drifted: list[str] = []
    if claude_ok and claude_expected is not None:
        if current_text(claude_path) != claude_expected:
            drifted.append(str(claude_path))
            if mode == "apply":
                write_text_atomic(claude_path, claude_expected)
        if mode == "apply":
            sidecar.setdefault("claude", {})[str(claude_path)] = sorted(claude_allow)

    if codex_ok and current_text(codex_path) != codex_expected:
        drifted.append(str(codex_path))
        if mode == "apply":
            if codex_expected is None:
                try:
                    codex_path.unlink()
                except FileNotFoundError:
                    pass
            else:
                write_text_atomic(codex_path, codex_expected)

    if mode == "apply":
        save_sidecar(environ, sidecar)
    return drifted, warnings


def print_invocations(environ: dict, script_name: str) -> tuple[list[str], list[str]]:
    warnings: list[str] = []
    claude_roots, _ = claude_plugin_roots(environ, warnings)
    codex_roots, _ = codex_plugin_roots(environ, warnings)
    roots = sorted(claude_roots | codex_roots)
    lines: list[str] = []
    for root in roots:
        requires = load_requires(root, warnings)
        if requires is None:
            continue
        for template in requires["permissions"]["claude_allow"]:
            if not (template.startswith("Bash(") and template.endswith(")")):
                continue
            inner = template[len("Bash("):-1]
            if script_name not in inner:
                continue
            forward, _ = harness_permissions.path_spellings(root)
            rendered = inner.replace(harness_permissions.PLUGIN_ROOT_TOKEN, forward)
            if rendered not in lines:
                lines.append(rendered)
    return lines, warnings


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--apply", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--print", dest="print_script", metavar="SCRIPT")
    args = parser.parse_args(argv)
    environ = os.environ
    try:
        if args.print_script:
            lines, warnings = print_invocations(environ, args.print_script)
            for line in lines:
                print(line)
            for warning in warnings:
                print(f"harness-permissions-sync: {warning}", file=sys.stderr)
            return 0
        mode = "apply" if args.apply else "check"
        drifted, warnings = synchronize(environ, mode)
        for warning in warnings:
            print(f"harness-permissions-sync: {warning}", file=sys.stderr)
        if drifted:
            verb = "Updated" if mode == "apply" else "Drift in"
            print(f"harness-permissions-sync: {verb}: " + ", ".join(drifted))
        if mode == "check" and not warnings:
            return 1 if drifted else 0
        return 0
    except Exception as error:  # noqa: BLE001
        print(f"harness-permissions-sync: {error}", file=sys.stderr)
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
